name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t todo-app .
      - name: Run tests
        run: docker run todo-app python -m unittest discover -s tests
